TabBar 를 Coordinator 로 연결
gabozzago/gabozzago-ios pull request #6
Opened 2022-08-05 14:41 UTC by Mindohyeon

## 개요
![Simulator Screen Shot - iPhone 12 - 2022-08-05 at 23 39 12](https://user-images.githubusercontent.com/81687906/183100303-5ac56ef0-d0f1-44e1-bb58-bb9822674426.png)

## 한 일
TabBaritem 에 있는 각각의 View 들을 Coordinator 로 연결함

> action 에러를 해결하면 navigation 이 겹쳐서 Bar 위치가 이상해지는 이슈가 있었는데  Coordnator 각각의 navigation을 초기화 해줌으로써 해결

2022-08-09 14:50 UTC, kimsh153 requested changes
코디네이터들 엔터같은거 하나로 통일해줘
TabBarCoordinator 코드 정리좀 해줘...

2022-08-09 14:50 UTC, kimsh153 commented on Project/Source/App/Coordinator/Main/MainCoordinator.swift
> +        print("createPost")
프린트 지워줘

2022-08-09 14:50 UTC, kimsh153 commented on Project/Source/App/Coordinator/TabBar/TabBarCoordinator.swift
> +
주석이랑 엔터 정리 좀 해줘

2022-08-09 14:50 UTC, kimsh153 commented on Project/Source/Presentation/Base/baseViewModel.swift
> +    var coordinator: baseCoordinator
이거 let으로 바꿔줘

2022-08-15 13:40 UTC, Mindohyeon commented on Project/Source/App/Coordinator/Main/MainCoordinator.swift
> +        print("createPost")
넹

2022-08-15 13:40 UTC, Mindohyeon commented on Project/Source/App/Coordinator/TabBar/TabBarCoordinator.swift
> +
넹

2022-08-15 13:47 UTC, kimsh153 requested changes

2022-08-15 13:47 UTC, kimsh153 commented on Project/Source/App/Coordinator/Profile/ProfileCoordinator.swift
> +    override func start() {
공백 하나만 넣어줘...

2022-08-15 13:50 UTC, kimsh153 approved these changes

2022-08-15 13:51 UTC, Heeesang approved these changes

2022-08-15 13:53 UTC, merged